spring.application.name=ecom

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=health,info

spring.datasource.url=SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db
spring.datasource.username=SPRING_DATASOURCE_USERNAME:root
spring.datasource.password=SPRING_DATASOURCE_PASSWORD

logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=default-secret-key-change-in-production-min-32-chars


email.from=onboarding@resend.dev

server.port=8080